# Generated by Django 4.0.1 on 2022-01-10 14:02

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=2560)),
                ('link', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='SubDatasource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_information', models.CharField(max_length=1024)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='dspdata.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='RawEmailData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', jsonfield.fields.JSONField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('content_raw', models.TextField(blank=True, null=True)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data', to='dspdata.subdatasource')),
            ],
        ),
        migrations.CreateModel(
            name='EmailDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'NamedEntity'), (2, 'ExternalReference'), (3, 'Other')], null=True)),
                ('value', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datapoints', to='dspdata.rawemaildata')),
            ],
        ),
    ]
