# Generated by Django 3.2.11 on 2022-01-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dspdata', '0002_alter_emaildatapoint_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildatapoint',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Tokenization'), (2, 'Tfidf'), (3, 'Named Entity'), (4, 'Cluster')], null=True),
        ),
    ]
