import nltk
from nltk import WordNetLemmatizer
from spacy.lang.en import English

nlp = English()

wordnet_lemmatizer = WordNetLemmatizer()
words = set(nltk.corpus.words.words())
punctuation = "!\"#$%&'()*+, -./:;<=>?@[\]^_`{|}~"

list_of_scam_words = [
    "Action",
    "Buy",
    "Call",
    "Clearance",
    "Expire",
    "Get",
    "Instant",
    "Urgent",
    "Bonus",
    "Bargain",
    "Free",
    "Prize",
    "Deal",
    "Unlimited",
    "Acceptance",
    "Access",
    "Boss",
    "Cancel",
    "Certified",
    "Cheap",
    "Compare",
    "Congratulations",
    "Cures",
    "Dear",
    "Friend",
    "Debt",
    "Guarantee",
    "Guaranteed",
    "Hello",
    "Offer",
    "Opportunity",
    "Winner",
    "Winning",
    "Won",
    "Selected",
    "Amazing",
    "Billion",
    "Cash",
    "Credit",
    "Earn",
    "Extra",
    "Home",
    "Income",
    "Lose",
    "Vacation",
    "Addresses",
    "Beneficiary",
    "Billing",
    "Casino",
    "Celebrity",
    "Hidden",
    "Investment",
    "Junk",
    "Legal"
    "Loan",
    "Lottery",
    "Medicine",
    "Miracle",
    "Money",
    "Nigerian",
    "Offshore",
    "Password",
    "Passwords",
    "Refinance",
    "Request",
    "Rolex",
    "Score",
    "Spam",
    "Dollars",
    "Dollar",
    "Euro",
    "Valium",
    "Viagra",
    "Vicodin",
    "Warranty",
    "Xanax",
]

list_of_two_grams = [
    ("Act", "now"),
    ("Apply", "now"),
    ("Apply", "online"),
    ("Buy", "direct"),
    ("Call", "now"),
    ("Click", "here"),
    ("Drastically", "Reduced"),
    ("Exclusive", "Deal"),
    ("Do", "it"),
    ("Get", "it"),
    ("Get", "started"),
    ("Important", "information"),
    ("Information", "regarding"),
    ("Limited", "time"),
    ("New", "customers"),
    ("Customers", "only"),
    ("Now", "only"),
    ("Offer", "expires"),
    ("Once", "in"),
    ("A", "lifetime"),
    ("Order", "now"),
    ("Please", "read"),
    ("Special", "promotion"),
    ("Take", "action"),
    ("While", "stocks"),
    ("Stocks", "last"),
    ("Best", "price"),
    ("Email", "marketing"),
    ("Instant", "access"),
    ("Free", "gift"),
    ("Free", "trial"),
    ("Great", "offer"),
    ("Incredible", "deal"),
    ("Satisfaction", "guaranteed"),
    ("Click", "here"),
    ("Click", "below"),
    ("Direct", "mail"),
    ("Direct", "marketing"),
    ("Order", "now"),
    ("Order", "today"),
    ("Avoid", "bankruptcy"),
    ("Card", "accepted"),
    ("Compare", "rates"),
    ("Credit", "card"),
    ("Card", "offers"),
    ("Dear", "friend"),
    ("Drastically", "reduced"),
    ("Easy", "terms"),
    ("Free", "grant"),
    ("Grant", "money"),
    ("Free", "hosting"),
    ("Free", "info"),
    ("Free", "membership"),
    ("Giving", "away"),
    ("Join", "millions"),
    ("Age", "restrictions"),
    ("No", "catch"),
    ("No", "experience"),
    ("No", "oblication"),
    ("No", "purchase"),
    ("Purchase", "necessary"),
    ("No", "questions"),
    ("Questions", "asked"),
    ("No", "strings"),
    ("Strings", "attached"),
    ("Save", "big"),
    ("Additional", "income"),
    ("All", "natural"),
    ("Big", "bucks"),
    ("Billion", "dollars"),
    ("Cash", "bonus"),
    ("Double", "your"),
    ("Earn", "cash"),
    ("Earn", "extra"),
    ("Extra", "cash"),
    ("Bad", "credit"),
    ("Eliminate", "debt"),
    ("Fantastical", "deal"),
    ("Financial", "freedom"),
    ("Free", "investment"),
    ("Free", "money"),
    ("Get", "paid"),
    ("Home", "based"),
    ("Increase", "sales"),
    ("Increase", "traffic"),
    ("Lose", "weight"),
    ("Money", "back"),
    ("No", "catch"),
    ("No", "fees"),
    ("No", "hidden"),
    ("Hidden", "costs"),
    ("No", "strings"),
    ("strings", "attached"),
    ("Potential", "earnings"),
    ("Pure", "profit"),
    ("Removes", "wrinkles"),
    ("Reverse", "aging"),
    ("Risk", "free"),
    ("Serious", "cash"),
    ("Stop", "snoring"),
    ("Vacation", "offers"),
    ("Weekend", "getaway"),
    ("Weight", "loss"),
    ("While", "you"),
    ("you", "sleep"),
    ("Child", "support"),
    ("Viagra", "delivery"),
    ("Human", "growth"),
    ("Life", "insurance"),
    ("Luxury", "car"),
    ("Meet", "singles"),
    ("Online", "degree"),
    ("Online", "pharmacy"),
    ("Undisclosed", "recipient"),
    ("University", "diplomas"),
    ("Unsecured", "credit"),
    ("US", "dollars"),
]
